services:
  scheduler:
    image: airflow-local-scheduler:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/opt/airflow/src
      - ./src/airflow_dags/dags:/opt/airflow/dags
      - ./src/airflow_dags/plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    environment:
      PYTHONPATH: "/opt/airflow/src"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/logs/airflow.db"
      ENVIRONMENT: "dev"
      AWS_ACCESS_KEY_ID: "dummy_key"
      AWS_SECRET_ACCESS_KEY: "dummy_secret"
      AWS_DEFAULT_REGION: "eu-west-1"
    networks:
          - airgap

  webserver:
    image: airflow-local-webserver:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/opt/airflow/src
      - ./src/airflow_dags/dags:/opt/airflow/dags
      - ./src/airflow_dags/plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    ports:
          - "4040:8080"
    environment:
      PYTHONPATH: "/opt/airflow/src"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/logs/airflow.db"
      ENVIRONMENT: "dev"
      AWS_ACCESS_KEY_ID: "dummy_key"
      AWS_SECRET_ACCESS_KEY: "dummy_secret"
      AWS_DEFAULT_REGION: "eu-west-1"
    networks:
          - airgap     # Talks to the scheduler securely
          - ui-bridge  # Opens the door to the browser
    # This explicitly deletes the hidden base hook entirely so it cannot run.
    post_start: !reset [ ]

networks:
  airgap:
    internal: true  # Blocks internet access
  ui-bridge:
    driver: bridge  # Allows localhost port mapping